# General
title: Metro Ideas Project

# Accounts
facebook: metroideas
github: metroideas
instagram: metroideas
twitter: thinkmetro
email: info@metroideas.org

# Build
# Collections
# Defaults
# Assets
# API keys