---
title: Metro Ideas Project
timezone: America/New_York
collections:
  asides:
    title: Asides
    output: false
  authors:
    title: Authors
    output: true
    permalink: "/staff/:title/"
  posts:
    title: Articles
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
    permalink: "/media/:path"
defaults:
- scope:
    path: ''
  values:
    image: 
    description: 
- scope:
    path: pages
    type: pages
  values:
    sections:
    - title: 
      image: 
      description: 
- scope:
    path: ''
    type: asides
  values:
    article:
- scope:
    path: ''
    type: authors
  values:
    layout: staff
    current: true
    role: 
    email: 
    twitter: 
- scope:
    path: ''
    type: posts
  values:
    permalink: /blog/:title/
    layout: article
    author: 
    project:
- scope:
    path: ''
    type: projects
  values:
    layout:
    authors: 
facebook: metroideas
github: metroideas
instagram: metroideas
twitter: thinkmetro
email: info@metroideas.org
nav:
- title: Home
  icon: logo
  href: "/"
- title: About
  icon: 
  href: "/about/"
- title: Research
  icon: 
  href: "/projects/"
- title: Blog
  icon: 
  href: "/blog/"
include: 
exclude:
- node_modules/
- bower_components/
- tmp/
- bower.json
- Gemfile*
- gulpfile.js
- package.json
- README.md
- LICENSE
- jekyll-build-error.log
- npm-debug.log
gems:
- jekyll-feed
- jekyll-redirect-from
- jekyll-sitemap
api:
  analytics: 
  facebook: 
  mailchimp: 
