---
title: Metro Ideas Project
timezone: America/New_York
collections:
  posts:
    title: Articles
    output: true
  asides:
    title: Asides
    output: false
  authors:
    title: Authors
    output: true
    permalink: "/staff/:title/"
  projects:
    title: Projects
    output: true
    permalink: "/projects/:title/"
  uploads:
    title: Uploads
    output: true
    permalink: "/media/:path"
defaults:
- scope:
    path: ''
  values:
    description: 
    lead: 
    author: []
    image:
      file: 
      caption: 
      credit: 
      alt: 
- scope:
    path: ''
    type: asides
  values:
    article: 
- scope:
    path: ''
    type: authors
  values:
    layout: staff
    main: staff
    current: true
    role: 
    email: 
    twitter: 
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: article
    main: article
    project: 
- scope:
    path: ''
    type: projects
  values:
    layout: project
    lead: 
    about: 
    article: []
    further reading:
    - title: 
      url: 
      description: 
    downloads:
    - title: 
      file: 
url: https://metroideas.org
description: We are an urban policy startup working for U.S. cities.
public: true
facebook: metroideas
github: metroideas
instagram: metroideas
twitter: thinkmetro
email: info@metroideas.org
include:
- _pages
exclude:
- Gemfile*
- gulpfile.js
- gulp.config.js
- node_modules/
- package.json
- package-lock.json
- README.md
- LICENSE
- jekyll-build-error.log
- npm-debug.log
- tmp/
- webpack.config.js
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-archives
- jekyll/imgix
imgix:
  source: metro-ideas-project.imgix.net
jekyll-archives:
  enabled:
  - categories
  - tags
  layout: archive
  permalinks:
    category: "/archives/category/:name/"
    tag: "/archives/tag/:name/"
google_analytics: UA-68712194-1
facebook_id: 225621571136193

# HCDE Tax Calculator
hcde_image_path: 'https://s3.amazonaws.com/hcde-calculator-images/'
page_gen:
  - data: 'hcde-calculator'
    template: hcde-calc
    name: 'title'
    dir: 'projects/hcde-tax-calculator/results'
    index_files: true
