---
# General
title: Metro Ideas Project
timezone: America/New_York

# Contact
facebook: metroideas
github: metroideas
instagram: metroideas
twitter: thinkmetro
email: info@metroideas.org

# Collections
collections:
  authors:
    title: Authors
    output: true
    permalink: /staff/:title/

  posts:
    title: Blog
    output: true
    permalink: /blog/:title/

  projects:
    title: Projects
    output: true
    permalink: /projects/:path/

  public:
    output: true
    permalink: /:path

  uploads:
    title: Uploads
    output: true
    permalink: /media/:path

# Defaults
defaults:

# Build settings
include:

exclude:
  - node_modules/
  - bower_components/
  - tmp/
  - bower.json
  - Gemfile*
  - gulpfile.js
  - package.json
  - README.md
  - LICENSE

# Plugins
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# API keys
api:
